language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kevkish/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kevkish/docker-react npm run test -- --watchAll=false